name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: build crx and xpi
    strategy:
      matrix:
        node:
          - 12
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: sudo apt --yes update
      - run: sudo apt --yes install xvfb
      - id: get_version
        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: xvfb-run --auto-servernum google-chrome --pack-extension=./crx
      - run: mv crx.crx nochmos.crx
      - uses: actions/upload-artifact@master
        with:
          name: nochmos.crx
          path: nochmos.crx
      - run: yarn run release:xpi
      - uses: actions/upload-artifact@master
        with:
          name: nochmos.xpi
          path: nochmos.xpi
      - id: create_release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
      - uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nochmos.crx
          asset_name: nochmos.crx
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nochmos.xpi
          asset_name: nochmos.xpi
          asset_content_type: application/zip
